### 사용자 추가1
POST http://localhost:8080/users/enrolls
Content-Type: application/json

[
  {
    "githubName": "JxxHxxx"
  },
  {
    "githubName": "TheDevLuffy"
  },
  {
    "githubName": "tkleskrlk2423"
  },
  {
    "githubName": "fredlee613"
  },
  {
    "githubName": "hyunjunhwang1994"
  },
  {
    "githubName": "dong-fa"
  },
  {
    "githubName": "AngelaChaejung"
  },
  {
    "githubName": "rylynntruth"
  },
  {
    "githubName": "hwi3721"
  },
  {
    "githubName": "HYEchive"
  },
  {
    "githubName": "Choboza"
  },
  {
    "githubName": "sirenabada"
  }
]

### 최근 푸시된 레포지토리 생성
GET http://localhost:8080/commits/renew

### 사용자 활성화 여부 & 요청일 커밋 여부 확인 배치
POST http://localhost:8080/batch/run
Content-Type: application/json

{
  "jobName" : "commit.check.job",
  "jobParameters" : {
    "executeSystem":"API",
    "id" : "ADMIN20240201-1",
    "sinceTime" : "2024-01-31T15:00:00Z"
  }
}

###
GET http://localhost:8080/api/job-executions/5/step-executions/5