### 사용자 등록
POST http://localhost:8080/github-members
Content-Type: application/json

[
  {"githubName": "p1ants"}, {"githubName": "TheDevLuffy"}, {"githubName": "tkleskrlk2423"}, {"githubName": "fredlee613"},
  {"githubName": "hyunjunhwang1994"}, {"githubName": "dong-fa"}, {"githubName": "AngelaChaejung"}, {"githubName": "rylynntruth"},
  {"githubName": "hwi3721"}, {"githubName": "HYEchive"}, {"githubName": "Choboza"}, {"githubName": "sirenabada"},
  {"githubName": "rickiepark"}, {"githubName":"madvirus"}, {"githubName":"jxxHxxx"}
]

### 사용자 활성화 여부 & 요청일 커밋 여부 확인 배치
POST http://localhost:8080/batch/run
Content-Type: application/json

{
  "jobName" : "commit-check.job",
  "jobParameters" : {
    "executeSystem":"API",
    "id" : "ADMIN20240218-04",
    "sinceTime" : "2024-02-18T00:00:00Z"
  }
}

### 최근 푸시된 레포지토리 정보 생성/갱신 모든 유저
PATCH http://localhost:8080/today-commits/renew-repo-name?since=2024-02-17T00:00:00Z

### 최근 푸시된 레포지토리 정보 생성/갱신 단건
PATCH http://localhost:8080/today-commits/24/check-commit?since=2024-02-17T00:00:00Z

